config/routes.rb
Rails.application.routes.draw do
  resources :invoices do
    collection do
      match 'search' => 'invoices#search', via: [:get, :post], as: :search
    end
  end

  root 'invoices#index'
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  def self.delete_old
  	@old_invoices = Invoice.where('date < ?', 30.days.ago)
  	@old_invoices.delete_all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @search = Invoice.search(params[:q])
    @invoices = @search.result

  end

  def search
    index
    render :index
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:amount, :company, :contragent, :currency, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<div class="col-xs-12">
<%= simple_form_for(@invoice) do |f| %>
  <div id="invoice-wrap">
    <%= f.error_notification %>
    <div class="row">
      <div class="col-xs-12">
        <h3 class="page-header">INVOICE<small class="pull-right">Date: <span class="invoice_header_date"></span></small></h3>
      </div><!-- /.col -->
    </div>

    <div class="row invoice-info">
      <div class="col-xs-4 invoice-col">
        From
        <address>
          <%= f.input_field :company, class: "form-control", id: "1" %>
          <input class="form-control" id= "2"  placeholder="address line 1" />
          <input class="form-control" id= "3"  placeholder="address line 2" />
          <input class="form-control" id= "4"  placeholder="phone number" />
        </address>
      </div><!-- /.col -->
      <div class="col-xs-4 invoice-col">
        To
        <address>
          <%= f.input_field :contragent, class: "form-control", id: "5" %>
          <input class="form-control" id= "6"  placeholder="address line 1" />
          <input class="form-control" id= "7"  placeholder="address line 2" />
          <input class="form-control" id= "8"  placeholder="phone number" />
        </address>
      </div><!-- /.col -->
      <div class="col-xs-4 invoice-col">
        <form class="form-horizontal">

          <div class="form-group">
            <div class="col-xs-4"><label>Invoice #</label></div>
            <div class="col-xs-8 invoice_num"><span id="invoice_number"><%= (Invoice.last.present? ? (Invoice.last.id + 1) : 1) %></span></div>
          </div>
          <div class="col-xs-12"></div>
          <div class="form-group">
            <div class="col-xs-4"><%= f.label :date, required: false %></div>
            <div class="col-xs-8"><%= f.input_field :date, class: "form-control datepicker", as: :string, id: "invoice_date" %></div>
          </div>

          <div class="col-xs-12"></div>
          <div class="form-group">
            <div class="col-xs-4"><%= f.label :currency, required: false %></div>
            <div class="col-xs-8"><%= f.input_field :currency, id:"invoice_currency", class: "form-control" %></div>
          </div>


          <div class="col-xs-12"></div>
          <div class="form-group">
            <div class="col-xs-5 invoice_space"><label>Amount due</label></div>
            <div class="col-xs-7 invoice_space bold" style="text-align:right; padding-top:7px"><span class="due">875.00</span><span class="subtotal_currency"></span></div>
          </div>
        </form>
      </div><!-- /.col -->
    </div><!-- /.row -->

    <div class="row">
      <div class="col-xs-12 table-responsive">
        <hr>
        <table class="table table-hover" id="items">
      
          <thead>
              <th class="item-name">Item</th>
              <th class="description">Description</th>
              <th class="unit">Unit Cost</th>
              <th class="quantity">Quantity</th>
              <th class="units">Price</th>
              <th class="no_print">Actions</th>
          </thead>
      
          <tbody>
            <tr class="item-row">
              <td><input class="form-control item_name" value="Item #1" /></td>
              <td><input class="form-control item_desc" value="Description" /></td>
              <td><input class="form-control cost" value="650.00" /></td>
              <td><input class="form-control qty" value="1" /></td>
              <td class="price_td"><span class="price">650.00</span><span class="subtotal_currency"></span></td>
              <td class="delete_td"><a class="delete" href="javascript:;" title="Remove row"><span class="ti-close"></span></a></td>
            </tr>
          
            <tr class="item-row">
              <td><input class="form-control item_name" value="Item #2" /></td>

              <td><input class="form-control item_desc" value="Description #2" /></td>
              <td><input class="form-control cost" value="75.00" /></td>
              <td><input class="form-control qty" value="3" /></td>
              <td class="price_td"><span class="price">225.00</span><span class="subtotal_currency"></span></td>
              <td class="delete_td"><a class="delete" href="javascript:;" title="Remove row"><span class="ti-close"></span></a></td>
            </tr>
          
            <tr id="hiderow">
              <td colspan="6"><a id="addrow" class="btn btn-success btn-sm" href="javascript:;" title="Add a row"><span class="ti-plus"></span>  Add a row</a></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-6 col-xs-offset-6">
        <div class="table-responsive">
          <table class="table table-hover" id="totals">
            <tr>
              <th style="width:50%">Subtotal:</th>
              <td><span id="subtotal">875.00</span><span class="subtotal_currency"></span></td>
            </tr>
            <tr>
              <th>Tax:</th>
              <td><input id="9" class="form-control" value="0.00" /></td>
            </tr>
            <tr>
              <th>Total:</th>
              <td class="balance"><span class="due" id="invoice_total">875.00</span><span class="subtotal_currency"></span></td>
              <%=f.hidden_field :amount, id: "invoice_total1" %>
            </tr>
          </table>
        </div>
      </div><!-- /.col -->    
    </div>

    <div class="row">
      <div class="col-xs-12 pull-left">
        <a class="btn btn-info btn-sm" id="invoice_button" data-toggle="modal" data-target="#invoice_modal">Show Invoice</a>
        <%= f.button :submit, 'Submit Payment', class: 'btn btn-warning btn-sm', id: "submit_invoice" %>    
      </div>
    </div>

    <div id="terms">
      <h5>Terms</h5>
      <textarea id="10">Payment terms: net 30. Interest accrued at 1.5% per month thereafter.</textarea>
    </div>
  </div>
  <% end %>
</div>

<div class="modal fade" id="invoice_modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg">
    <div class="modal-content" style="width:920px">
      <div class="container-fluid invoice_wrapper" style="margin:10px" id="print-me">
        <%= render 'invoice' %>
      </div>
      <div class="modal-footer">
        <button class="btn btn-primary" onclick="printDiv('print-me')">Print</button>
      </div>
    </div>
  </div>
</div>

app/views/invoices/_invoice.html.erb
<div class="row">
  <div class="col-xs-12">
    <h3 class="page-header">
      INVOICE
      <small class="pull-right">Date: <span class="invoice_header_date"></span></small>
    </h3>
  </div><!-- /.col -->
</div>
                <!-- info row -->
<div class="row invoice-info">
  <div class="col-xs-4 invoice-col">
    From
    <address>
      <div id= "modal_1" class="bold"></div>
      <div id= "modal_2"></div>
      <div id= "modal_3"></div>
      <div id= "modal_4"></div>

    </address>
  </div><!-- /.col -->

  <div class="col-xs-4 invoice-col">
    To
    <address>
      <div id= "modal_5"></div>
      <div id= "modal_6"></div>
      <div id= "modal_7"></div>
      <div id= "modal_8"></div>
    </address>
  </div><!-- /.col -->

  <div class="col-xs-4 invoice-col">
    <form class="form-horizontal">
      <div class="form-group">
        <div class="col-xs-5"><label>Invoice #</label></div>
        <div class="col-xs-7"><p id="modal_invoice_number" class="pull-right"></p></div>
      </div>
                    
      <div class="col-xs-12"></div>

      <div class="form-group">
        <div class="col-xs-4"><label>Date</label></div>
        <div class="col-xs-8"><span class="invoice_header_date pull-right"></span></div>
      </div>
                    
      <div class="col-xs-12"></div>

      <div class="form-group">
        <div class="col-xs-5 invoice_space"><label>Amount due</label></div>
        <div class="col-xs-7 invoice_space bold" style="text-align:right"><span class="due">875.00</span><span class="subtotal_currency"></span></div>
      </div>
    </form>
  </div><!-- /.col -->
</div><!-- /.row -->

<div class="row">
  <div class="col-xs-12">
    <hr>
    <table class="table table-bordered" id="modal_items">
      <thead>
        <th class="item-name">Item</th>
        <th class="description">Description</th>
        <th class="unit">Unit Cost</th>
        <th class="quantity">Quantity</th>
        <th class="units">Price</th>
      </thead>
      
      <tbody id="modal_tbody">
      </tbody>
    </table>

  </div>
</div>

<div class="row">
  <div class="col-xs-6 col-xs-offset-6">
    <div class="">
      <table class="table" id="modal_totals">
        <tr>
          <th style="width:50%">Subtotal:</th>
          <td><span id="modal_subtotal"></span><span class="subtotal_currency"></span></td>
        </tr>
        <tr>
          <th>Tax:</th>
          <td><span id="modal_9"></span><span class="subtotal_currency"></span></td>
        </tr>
        <tr>
          <th>Total:</th>
          <td class="balance"><span class="due">875.00</span><span class="subtotal_currency"></span></td>
        </tr>
      </table>
    </div>
  </div><!-- /.col -->
</div>

<div id="modal_terms">
  <h5>Terms</h5>
  <span id="modal_10"></span>
</div>

app/views/invoices/edit.html.erb
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="panel panel-default">
	      <div class="panel-heading">
	        <h3 class="panel-title">Edit Invoice</h3>
	        
	      </div>

	      <div class="panel-body">	
			<%= render 'form' %>
	      </div>
	      <div class="panel-footer">
	      	<%= link_to 'Back', invoices_path, class: 'btn btn-primary' %>
	        <%= link_to 'Show', @invoice, class: 'btn btn-success' %>
	      </div>
	    </div>
	</div>
</div>


 |

app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
      <div class="container-fluid">
        <div class="col-md-2">
          <%= link_to 'New Invoice', new_invoice_path, class: "btn btn-primary" %>
        </div>

        <%= search_form_for @search, url: search_invoices_path, html: {class: "form-inline col-md-8 col-md-offset-1", method: :post} do |f| %>
          <div class="input-daterange">
            <div class="col-md-4">
              <%= f.text_field :date_gteq, class: "form-control", placeholder: "Date >= to" %>
            </div>
            <div class="col-md-4 col-md-offset-1">
              <%= f.text_field :date_lteq, class: "form-control", placeholder: "Date <= to" %>
            </div>
          </div>

          <div class="col-md-2 col-md-offset-1 form-actions">
            <%= f.submit "Search", class: "btn btn-success" %>
          </div>
          
        <% end %>
      </div>

      </div>

      <div class="panel-body">
        <table class="table table-hover table-bordered">
          <thead>
            <tr>
              <th>Company</th>
              <th>Contragent</th>
              <th>Amount</th>
              <th>Date</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @invoices.each do |invoice| %>
              <tr>
                <td><%= invoice.company %></td>
                <td><%= invoice.contragent %></td>
                <td><%= invoice.amount %> <%= invoice.currency %></td>
                <td><%= invoice.date %></td>
                <td><%= link_to 'Show', invoice %></td>
                <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
                <td><%= link_to 'Delete', invoice, method: :delete, data: { confirm: 'Are you sure?'} %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <div class="panel-footer">
        
      </div>
    </div>
  </div> 
</div>

app/views/invoices/new.html.erb
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="panel panel-default">
	      <div class="panel-heading">
	        <%= link_to 'Back', invoices_path, class: 'btn btn-primary' %>
	      </div>

	      <div class="panel-body">	
			<%= render 'form' %>
	      </div>
	    </div>
	</div>
</div>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
      <h3 class="panel-title">Invoices</h3>
      </div>

      <div class="panel-body">
        <p>
          <strong>Company:</strong>
          <%= @invoice.company %>
        </p>

        <p>
          <strong>Contragent:</strong>
          <%= @invoice.contragent %>
        </p>

        <p>
          <strong>Amount:</strong>
          <%= @invoice.amount %> <%= @invoice.currency %>
        </p>

        <p>
          <strong>Date:</strong>
          <%= @invoice.date %>
        </p>
      </div>

      <div class="panel-footer">
        <div class="btn-group">
          <%= link_to 'Edit', edit_invoice_path(@invoice), class: "btn btn-success" %>
          <%= link_to 'Back', invoices_path, class: "btn btn-default" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SFInvoices</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="/">SERPforce Invoices</a>
	    </div>

	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
	      
	    </div>
	  </div>
	</nav>
	<div class="container-fluid">
		<%= yield %>
	</div>
</body>
</html>